version: 2.1

orbs:
  docker: circleci/docker@1

jobs:
  dockerlint:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ~/project/base/Dockerfile
      - docker/dockerlint:
          dockerfile: ~/project/node/Dockerfile

  push:
    parameters:
      push-sha:
        type: boolean
      push-stable:
        type: boolean
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - when:
          condition: << parameters.push-sha >>
          steps:
            - run: make -j3 VERSION=$(echo << pipeline.git.revision >> | cut -c -7) docker-push
      - when:
          condition: << parameters.push-stable >>
          steps:
            - run: make -j3 docker-push-stable

workflows:
  lint-push-sha: &lint-push
    jobs:
      - dockerlint
      - docker/hadolint:
          name: hadolint
          dockerfiles: base/Dockerfile:node/Dockerfile
          ignore-rules: 'DL3004,DL3013'
      - push:
          name: push
          push-sha: true
          push-stable: false
          requires:
            - dockerlint
            - hadolint
          filters:
            branches:
              ignore: master
      - push:
          name: push-stable
          push-sha: true
          push-stable: true
          requires:
            - dockerlint
            - hadolint
          filters:
            branches:
              only: master

  weekly-lint-push-stable:
    jobs:
      - dockerlint
      - docker/hadolint:
          name: hadolint
          dockerfiles: base/Dockerfile:node/Dockerfile
          ignore-rules: 'DL3004,DL3013'
      - push:
          name: weekly-push-stable
          push-sha: false
          push-stable: true
          requires:
            - dockerlint
            - hadolint
    triggers:
      - schedule:
          # Weekly on Wednesday
          cron: "0 0 * * 3"
          filters:
            branches:
              only: master
