version: 2.1

orbs:
  docker: circleci/docker@1

jobs:
  dockerlint:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ~/project/base/Dockerfile
      - docker/dockerlint:
          dockerfile: ~/project/node/Dockerfile

  push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - unless:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: make -j3 VERSION=$(echo << pipeline.git.revision >> | cut -c -7) docker-push
      - when:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: make -j3 docker-push
            - run: make -j3 docker-push-stable

workflows:
  lint-push: &lint-push
    jobs:
      - dockerlint
      - docker/hadolint:
          name: hadolint
          dockerfiles: base/Dockerfile,node/Dockerfile
          ignore-rules: 'DL3004,DL3013'
      - push:
          requires:
            - dockerlint
            - hadolint

  weekly-lint-push:
    <<: *lint-push
    triggers:
      - schedule:
          # Weekly on Monday
          cron: "0 0 * * 1"
          filters:
            branches:
              only: master
